# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/2.0/language-android/ for more details.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  android: circleci/android@1.0.3

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  Build-Release-Testing:
    # These next lines define the Android machine image executor.
    # See: https://circleci.com/docs/2.0/executor-types/
    executor:
      name: android/android-machine

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout

      # The next step will run the unit tests
      # - android/run-tests:
      #     test-command: ./gradlew lint testDebug --continue

      # Then start the emulator and run the Instrumentation tests!
      # - android/start-emulator-and-run-tests:
      #     test-command: ./gradlew connectedDebugAndroidTest
      #     system-image: system-images;android-25;google_apis;x86

      # And finally run the release build
      - run:
          name: Assemble Release Build
          command: |
            chmod +x gradlew
            ./gradlew assembleRelease

      # - run:
      #     name: Uploading Artifacts TO Goorm-Server
      #     command: |
      #       TIMESTAMP=`date '+%F_%H:%M:%S'`
      #       echo $RCLONE_INSTALL | base64 -di > install.sh
      #       chmod +x install.sh
      #       ./install.sh
      #       rclone copyto $PWD/app/build/outputs/apk/release goorm-server:/var/www/html/WebViewexample_CircleCI_$TIMESTAMP   
      - store_artifacts:
          path: $PWD/app/build/outputs/apk/release
  
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  Build_WebViewexample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - Build-Release-Testing